### ISSUE TITLE
"Treat Ungraded as 0"_ is checked." does not exist at the place pointed out

### ISSUE THREAD

**Issue by knightsamar** [stephenredfield/InstructorResources#2]
In [GradeSubmission](https://stephenredfield.github.io/InstructorResources/IssuingGrades.html), Step 2 says `2. Ensure the box _"Treat Ungraded as 0"_ is checked. ` but that option does not exist in the new Gradebook.

**Comment by stephenredfield** [comment]
Updated to new gradebook style.
